version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8185:80
    container_name: '${PROJECT_NAME}_nginx'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
    depends_on:
      - php
    restart: always

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: '${PROJECT_NAME}_php'
    environment:
      - mysql_host=mysql
      - mysql_database=${PROJECT_NAME}
      - mysql_user=${PROJECT_NAME}
      - mysql_password=${MYSQL_PASSWORD}
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always

  mysql:
    image: mysql:8.0.19
    container_name: '${PROJECT_NAME}_mysql'
    environment:
      - MYSQL_DATABASE=${PROJECT_NAME}
      - MYSQL_USER=${PROJECT_NAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./dump:/home/dump
    ports:
      - 3305:3306

  adminer:
    image: adminer
    container_name: '${PROJECT_NAME}_adminer'
    ports:
      - 8006:8080

volumes:
  mysql_volume:
